### ISSUE TITLE
Support for arm64-apple-macos

### ISSUE THREAD

**Issue by mschrage** [IBM-Swift/Kitura-WebSocket#108]
Hi there,

I am trying to compile a macOS app with a universal binary to support Apple Silicon. 

I am getting this error message:
```
Could not find module 'KituraWebSocket' for target 'arm64-apple-macos'; found: x86_64, x86_64-apple-macos
```

Are there any plans to add support for a `x86_64-apple-macos` target?

**Comment by mbarnach** [comment]
`swift test --arch arm64` works on an M1.
I can also run the tests from XCode (both M1 and Rosetta). 

Could this be an issue within your XCode project where the universal binary support is not set properly?
Is it working if: you try to compile only for ARM64; only for x86_64?

**Comment by mschrage** [comment]
Sorry for the slow response. You were spot on. This was an issue with my Xcode project config.
