### ISSUE TITLE
Add method for unregistering in WSConnectionUpgradeFactory.swift

### ISSUE THREAD

**Issue by eman6576** [IBM-Swift/Kitura-WebSocket#16]
Hello,

I have a feature request for this library. Is there a possibility that we can add the ability to unregister a service programmatically when it isn't needed anymore? I propose the method should look something like this from the application developer's perspective:

```swift
// Register service in main.swift
let service1 = GroupChatService()
WebSocket.register(service: service1, onPath: "service1")
let service2 = GroupChatService()
WebSocket.register(service: service1, onPath: "service2")
let service3 = GroupChatService()
WebSocket.register(service: service1, onPath: "service3")

// Services are being used by different clients...

// Lets remove service 2 since the group ended
Websocket.unregister(service: service2, onPath: "service2")

// Only service 1 and 3 are in use
```

The reason for this need is because if the service isn't needed anymore, we should be able to deallocate it to reduce the memory footprint on the server.

**Comment by shmuelk** [comment]
Please see issue IBM-Swift/Kitura#1113 it's already implemented awaiting the review and merge of the PR.
