### ISSUE TITLE
Chat example

### ISSUE THREAD

**Issue by noobiept** [IBM-Swift/Kitura-WebSocket#2]
Hello, so I've looked at the chat example and have some doubts about it.

On the readme example, it is using the 'connections' variable in 'ChatService' directly (without locks), but on the other chat example that you've written (https://github.com/IBM-Swift/Kitura-Chat-Server/blob/master/Sources/KituraChatServer/ChatService.swift#L26) you have a lock that is being used every time there's a read/write on 'connections' variable. Is each function running on a separate thread, and thus needing a lock, or is it something else? Which one is correct?

**Comment by shmuelk** [comment]
In general incoming messages to a single WebSocketService instance can come from multiple threads simultaneously. Unfortunately the Dictionary struct of Swift is not thread safe.

The example in the README.md is very simplified version of the server found in [Kitura-Chat-Server](https://github.com/IBM-Swift/Kitura-Chat-Server). One of the simplifications is the removal of the locking around the references to the variable connections.

I will add a comment to the READMEE.md to the affect that "in real applications one should add locking around the access of the connections Dictionary as messages may arrive in multiple threads".

Would that help clarify things here?

**Comment by noobiept** [comment]
Thanks for the help, yea I think its better to be clear on what is necessary to have a proper application.
