### ISSUE TITLE
Stale connections are never closed

### ISSUE THREAD

**Issue by bridger** [IBM-Swift/Kitura-WebSocket#24]
In my server I'm finding that there can be some stale connections which are never cleaned up. I'm not sure how to handle these.

One idea is to ping all the connections every X minutes. In this loop I could send a ping to any suspected-dead connections. However, I don't know how to tell if the connection sends a pong back.

It would be great if each WebsocketConnection could have a timestamp which shows the last time any data was received from the connection (including a pong). Then it would be easy to detect a dead connection.

**Comment by Andrew-Lees11** [comment]
PR #48 solves this issue using a timer on connections and a tunable extension to WebsocketService which sets how often the connections are checked.
