### ISSUE TITLE
Reflect WSS support in the README

### ISSUE THREAD

**Issue by TheSoundDefense** [IBM-Swift/Kitura-WebSocket#3]
Kitura-Websocket appears to support `wss` natively, but it took me a while to realize this because it's not reflected in the README. Perhaps something can be added to note this.

**Comment by shmuelk** [comment]
@TheSoundDefense Thanks for pointing this out to me.

I just pushed changes to the README to reflect this oversight.

Please tell me if it's still not clear enough.
