### ISSUE TITLE
Package no longer consistent

### ISSUE THREAD

**Issue by ahartman** [IBM-Swift/Kitura-WebSocket#30]
The readme.md describes a structure that is different from the actual contents; there is no directory ChatServer but one called KituraWebSocket. The package does not compile and produce errors: copyBytes must be copyMemory. I fixed those. Then the build is OK but I do not know the start command: ./.build/debug/???

Examples are the most important documentation available; I am looking to convert a PHP back end to a Kitura web-socket based server. Without a working example as a starting point that is hopeless. I would have expected examples under the umbrella of IBM to simply work.

I would appreciate enormously if somebody could rectify this example.
kind regards, André Hartman

**Comment by helenmasters** [comment]
André,

I've merged a PR which I *hope* addresses your concerns above.

I've fixed the compilation errors which I encountered trying to recreate your steps and have spent a while trying to clarify the wording within the example code. Please could you let me know whether these changes do or don't address your concerns and if you have further problems or concerns please open another issue as I'd be happy to take another look.

Regards,
Helen
