### ISSUE TITLE
Deprecation warnings on Swift 4.1 in README Example

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/Kitura-WebSocket#32]
Shihab, 
Please can you take a look at the Example in the README.md as the package now builds correctly (see #31 for the fixes I put in there), although on Swift 4.1 - there are still 3 warnings: 'copyBytes(from:count:)' is deprecated: renamed to 'copyMemory(from:byteCount:)'. Please could you investigate and resolve these.
Thanks.

**Comment by ShihabMehboob** [comment]
@helenmasters I've opened a PR in reference to this - https://github.com/IBM-Swift/Kitura-WebSocket/pull/33

**Comment by djones6** [comment]
The change to remove deprecation warnings is not yet tagged and there's another API breaking change in master (#28).  The next tag of master will need to be a major - or we could cherry-pick #33 in a patch off 1.0.1, if we think it's worth it.

The deprecation warnings in BlueCryptor have not been fixed yet (needs a PR), and it is also at 1.0 already.  Again, could patch off 0.8.x if we think it's worth it.

If we _do_ move to BlueCryptor 1.0 - which would make sense to include in a new major of WebSocket - we'll need to do the same in Kitura-Session and any other modules that could be used together, else it will require SPM to perform rollbacks.  This may be worth doing as a general piece of work to move the repos to use the 1.0 versions of Socket, Signals, SSLService, Cryptor etc.

**Comment by helenmasters** [comment]
As we have now tagged a version 2 I've tested building the README example against both Swift 4.1 and Swift 4.2 and both versions now pass without generating any deprecation warnings, so I'm closing this issue as it is now fixed.
