### ISSUE TITLE
Compression / permessage-deflate support

### ISSUE THREAD

**Issue by bridger** [IBM-Swift/Kitura-WebSocket#7]
I'd like to enable compression for binary data messages. Are there plans to support this websocket extension? [RFC 7692](https://tools.ietf.org/html/rfc7692)

It is supported in Chrome and Firefox. There is a client-side Swift implementation in https://github.com/tidwall/SwiftWebSocket which I will be using.

**Comment by Andrew-Lees11** [comment]
@bridger We are now looking into implementing compression for binary data messages and will keep you updated on any progress.

**Comment by bridger** [comment]
@Andrew-Lees11 Is this feature still be considered? I believe this would be a huge performance win for my application, which can send large websocket messages when loading the page.

**Comment by pushkarnk** [comment]
I've been thinking about how to implement `permessage-deflate` on the `websocket-nio` branch. I did some superficial reading of [RFC 7692](https://tools.ietf.org/html/rfc7692). I ran through the `NIOWebSocket` API and source code and it looks like we'd need to do this:

1. Extend (or reimplement?) the WebSocketUpgrader to handle the handshake/negotiation
2. Implement a message-to-message compressor, which is a ChannelDuplexHandler
3. In the server pipeline, the compressor/deflater must come after WebSocketFrameEncoder
4. Implement a message-to-message decompressor, which is a ChannelDuplexHandler
5. In the server pipeline, the decompressor/inflater comes in before the WebSocketFrameDecoder
6. The inflater/deflater would be implemented using something like zlib

This is my very high-level understanding for now. And I might be wrong!

**Comment by pushkarnk** [comment]
I've been able to do a basic prototype and run some of the compression tests in autobahn against it. Tests 12.1.1 to 12.1.10 which send simple compressed messages are passing. I'm now working to support fragmentation.

**Comment by pushkarnk** [comment]
listing some todos here
- [ ] handle `client-no-context-takeover` and `server-no-context-takeover` headers
- [ ] handle the `server_max_window_bits` and `client_max_window_bits` headers

**Comment by pushkarnk** [comment]
Added code to handle fragmented messages. With this an entire category of tests `12.X.X` in autobahn now pass.

**Comment by pushkarnk** [comment]
All autobahn test passing now. I've created a draft PR: https://github.com/IBM-Swift/Kitura-WebSocket/pull/81

A few TODOs pending.

**Comment by pushkarnk** [comment]
Added a PR to support WS extensions in Kitura-NIO: https://github.com/IBM-Swift/Kitura-NIO/pull/174
