### ISSUE TITLE
websocket-nio branch depends on BlueCryptor

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura-WebSocket#70]
As far as I can see, this is not used and could be removed?

https://github.com/IBM-Swift/Kitura-WebSocket/blob/8d034e969840d50f33477db2c816f290af9e94af/Package.swift#L33

**Comment by pushkarnk** [comment]
Raised a  [pull request](https://github.com/IBM-Swift/Kitura-WebSocket/pull/95) and got it merged. The related code has been now pushed to [Kitura-WebSocket-NIO](https://github.com/IBM-Swift/Kitura-WebSocket-NIO).
